
import java.awt.CardLayout;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        cardLayout = (CardLayout) mainPanel.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        HomeScreen = new javax.swing.JPanel();
        homeTop = new javax.swing.JPanel();
        addRoom = new javax.swing.JButton();
        hiUser = new javax.swing.JLabel();
        scrollRoom = new javax.swing.JScrollPane();
        roomList = new javax.swing.JPanel();
        room1 = new javax.swing.JButton();
        room2 = new javax.swing.JButton();
        room3 = new javax.swing.JButton();
        room4 = new javax.swing.JButton();
        room5 = new javax.swing.JButton();
        room6 = new javax.swing.JButton();
        room7 = new javax.swing.JButton();
        room8 = new javax.swing.JButton();
        room9 = new javax.swing.JButton();
        room10 = new javax.swing.JButton();
        Room = new javax.swing.JPanel();
        roomTop = new javax.swing.JPanel();
        dispRoomName = new javax.swing.JLabel();
        addRoom1 = new javax.swing.JButton();
        Return = new javax.swing.JButton();
        scrollRoom1 = new javax.swing.JScrollPane();
        roomList2 = new javax.swing.JPanel();
        appliance1 = new javax.swing.JButton();
        appliance2 = new javax.swing.JButton();
        appliance3 = new javax.swing.JButton();
        appliance4 = new javax.swing.JButton();
        appliance5 = new javax.swing.JButton();
        appliance6 = new javax.swing.JButton();
        appliance7 = new javax.swing.JButton();
        appliance8 = new javax.swing.JButton();
        appliance9 = new javax.swing.JButton();
        appliance10 = new javax.swing.JButton();
        roomReg = new javax.swing.JPanel();
        roomRegTop = new javax.swing.JPanel();
        Return1 = new javax.swing.JButton();
        dispRoomName1 = new javax.swing.JLabel();
        receiveRoom = new javax.swing.JTextField();
        confirmAdd = new javax.swing.JButton();
        cancelAdd = new javax.swing.JButton();
        applianceReg = new javax.swing.JPanel();
        applianceTop = new javax.swing.JPanel();
        dispRoomName2 = new javax.swing.JLabel();
        Return2 = new javax.swing.JButton();
        receiveRoom1 = new javax.swing.JTextField();
        confirmAdd1 = new javax.swing.JButton();
        cancelAdd1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 1000));

        mainPanel.setPreferredSize(new java.awt.Dimension(337, 600));
        mainPanel.setLayout(new java.awt.CardLayout());

        HomeScreen.setPreferredSize(new java.awt.Dimension(337, 600));

        addRoom.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        addRoom.setText("+");
        addRoom.setAlignmentX(0.5F);
        addRoom.setMaximumSize(new java.awt.Dimension(70, 70));
        addRoom.setPreferredSize(new java.awt.Dimension(70, 70));
        addRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomActionPerformed(evt);
            }
        });

        hiUser.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        hiUser.setText("Hi, [User]");

        javax.swing.GroupLayout homeTopLayout = new javax.swing.GroupLayout(homeTop);
        homeTop.setLayout(homeTopLayout);
        homeTopLayout.setHorizontalGroup(
            homeTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTopLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(hiUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        homeTopLayout.setVerticalGroup(
            homeTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hiUser)
                .addGap(17, 17, 17))
        );

        scrollRoom.setBorder(null);
        scrollRoom.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollRoom.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollRoom.setPreferredSize(new java.awt.Dimension(337, 482));

        room1.setText("room1");
        room1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room1ActionPerformed(evt);
            }
        });

        room2.setText("jButton1");

        room3.setText("jButton1");

        room4.setText("room1");
        room4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room4ActionPerformed(evt);
            }
        });

        room5.setText("room1");
        room5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room5ActionPerformed(evt);
            }
        });

        room6.setText("jButton1");

        room7.setText("room1");
        room7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room7ActionPerformed(evt);
            }
        });

        room8.setText("jButton1");

        room9.setText("room1");
        room9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room9ActionPerformed(evt);
            }
        });

        room10.setText("jButton1");

        javax.swing.GroupLayout roomListLayout = new javax.swing.GroupLayout(roomList);
        roomList.setLayout(roomListLayout);
        roomListLayout.setHorizontalGroup(
            roomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomListLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(roomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roomListLayout.createSequentialGroup()
                        .addComponent(room1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(room2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roomListLayout.createSequentialGroup()
                        .addComponent(room4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(room3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roomListLayout.createSequentialGroup()
                        .addComponent(room5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(room6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roomListLayout.createSequentialGroup()
                        .addComponent(room7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(room8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roomListLayout.createSequentialGroup()
                        .addComponent(room9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(room10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roomListLayout.setVerticalGroup(
            roomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(room1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(room4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(room5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(room7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(room9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        scrollRoom.setViewportView(roomList);
        roomList.getAccessibleContext().setAccessibleName("roomList");

        javax.swing.GroupLayout HomeScreenLayout = new javax.swing.GroupLayout(HomeScreen);
        HomeScreen.setLayout(HomeScreenLayout);
        HomeScreenLayout.setHorizontalGroup(
            HomeScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeScreenLayout.createSequentialGroup()
                .addComponent(scrollRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
            .addGroup(HomeScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        HomeScreenLayout.setVerticalGroup(
            HomeScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        scrollRoom.getAccessibleContext().setAccessibleName("scrollRoom");

        mainPanel.add(HomeScreen, "homescreen");
        HomeScreen.getAccessibleContext().setAccessibleName("homescreen");

        Room.setPreferredSize(new java.awt.Dimension(337, 600));

        dispRoomName.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        dispRoomName.setText("[Room]");

        addRoom1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        addRoom1.setText("+");
        addRoom1.setAlignmentX(0.5F);
        addRoom1.setMaximumSize(new java.awt.Dimension(70, 70));
        addRoom1.setPreferredSize(new java.awt.Dimension(70, 70));
        addRoom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoom1ActionPerformed(evt);
            }
        });

        Return.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Return.setText("<");
        Return.setAlignmentX(0.5F);
        Return.setMaximumSize(new java.awt.Dimension(70, 70));
        Return.setPreferredSize(new java.awt.Dimension(70, 70));
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roomTopLayout = new javax.swing.GroupLayout(roomTop);
        roomTop.setLayout(roomTopLayout);
        roomTopLayout.setHorizontalGroup(
            roomTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomTopLayout.createSequentialGroup()
                .addGroup(roomTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roomTopLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Return, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomTopLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dispRoomName)
                        .addGap(46, 46, 46)))
                .addComponent(addRoom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        roomTopLayout.setVerticalGroup(
            roomTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Return, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(dispRoomName)
                .addContainerGap())
            .addGroup(roomTopLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(addRoom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scrollRoom1.setBorder(null);
        scrollRoom1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollRoom1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollRoom1.setPreferredSize(new java.awt.Dimension(337, 482));

        roomList2.setPreferredSize(new java.awt.Dimension(300, 500));

        appliance1.setText("lamp");
        appliance1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appliance1ActionPerformed(evt);
            }
        });

        appliance2.setText("jButton1");

        appliance3.setText("lamp");
        appliance3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appliance3ActionPerformed(evt);
            }
        });

        appliance4.setText("jButton1");

        appliance5.setText("lamp");
        appliance5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appliance5ActionPerformed(evt);
            }
        });

        appliance6.setText("jButton1");

        appliance7.setText("jButton1");

        appliance8.setText("lamp");
        appliance8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appliance8ActionPerformed(evt);
            }
        });

        appliance9.setText("lamp");
        appliance9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appliance9ActionPerformed(evt);
            }
        });

        appliance10.setText("jButton1");

        javax.swing.GroupLayout roomList2Layout = new javax.swing.GroupLayout(roomList2);
        roomList2.setLayout(roomList2Layout);
        roomList2Layout.setHorizontalGroup(
            roomList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomList2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(roomList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roomList2Layout.createSequentialGroup()
                        .addComponent(appliance1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(appliance2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roomList2Layout.createSequentialGroup()
                        .addComponent(appliance3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(appliance4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roomList2Layout.createSequentialGroup()
                        .addComponent(appliance5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(appliance6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roomList2Layout.createSequentialGroup()
                        .addComponent(appliance8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(appliance7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roomList2Layout.createSequentialGroup()
                        .addComponent(appliance9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(appliance10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roomList2Layout.setVerticalGroup(
            roomList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomList2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roomList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appliance1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appliance2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roomList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appliance3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appliance4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roomList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appliance5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appliance6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roomList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appliance8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appliance7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roomList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appliance9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appliance10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        scrollRoom1.setViewportView(roomList2);

        javax.swing.GroupLayout RoomLayout = new javax.swing.GroupLayout(Room);
        Room.setLayout(RoomLayout);
        RoomLayout.setHorizontalGroup(
            RoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RoomLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(roomTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(scrollRoom1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE))
                .addContainerGap())
        );
        RoomLayout.setVerticalGroup(
            RoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roomTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollRoom1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(Room, "room");
        Room.getAccessibleContext().setAccessibleName("room");

        roomReg.setPreferredSize(new java.awt.Dimension(337, 600));

        Return1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Return1.setText("<");
        Return1.setAlignmentX(0.5F);
        Return1.setMaximumSize(new java.awt.Dimension(70, 70));
        Return1.setPreferredSize(new java.awt.Dimension(70, 70));
        Return1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return1ActionPerformed(evt);
            }
        });

        dispRoomName1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        dispRoomName1.setText("Room Name:");

        javax.swing.GroupLayout roomRegTopLayout = new javax.swing.GroupLayout(roomRegTop);
        roomRegTop.setLayout(roomRegTopLayout);
        roomRegTopLayout.setHorizontalGroup(
            roomRegTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomRegTopLayout.createSequentialGroup()
                .addGroup(roomRegTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roomRegTopLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(dispRoomName1))
                    .addGroup(roomRegTopLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Return1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roomRegTopLayout.setVerticalGroup(
            roomRegTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomRegTopLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Return1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dispRoomName1)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        receiveRoom.setText("[ENTER ROOM NAME]");
        receiveRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveRoomActionPerformed(evt);
            }
        });

        confirmAdd.setText("confirm");

        cancelAdd.setText("cancel");

        javax.swing.GroupLayout roomRegLayout = new javax.swing.GroupLayout(roomReg);
        roomReg.setLayout(roomRegLayout);
        roomRegLayout.setHorizontalGroup(
            roomRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomRegLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(roomRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receiveRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roomRegLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(cancelAdd)
                        .addGap(47, 47, 47)
                        .addComponent(confirmAdd)))
                .addContainerGap(78, Short.MAX_VALUE))
            .addComponent(roomRegTop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        roomRegLayout.setVerticalGroup(
            roomRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomRegLayout.createSequentialGroup()
                .addComponent(roomRegTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(receiveRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addGroup(roomRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelAdd)
                    .addComponent(confirmAdd))
                .addGap(253, 253, 253))
        );

        mainPanel.add(roomReg, "roomReg");
        roomReg.getAccessibleContext().setAccessibleName("roomReg");

        applianceReg.setPreferredSize(new java.awt.Dimension(337, 600));

        dispRoomName2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        dispRoomName2.setText("Appliance Name:");

        Return2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Return2.setText("<");
        Return2.setAlignmentX(0.5F);
        Return2.setMaximumSize(new java.awt.Dimension(70, 70));
        Return2.setPreferredSize(new java.awt.Dimension(70, 70));
        Return2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout applianceTopLayout = new javax.swing.GroupLayout(applianceTop);
        applianceTop.setLayout(applianceTopLayout);
        applianceTopLayout.setHorizontalGroup(
            applianceTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, applianceTopLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(applianceTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(applianceTopLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(dispRoomName2))
                    .addComponent(Return2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );
        applianceTopLayout.setVerticalGroup(
            applianceTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, applianceTopLayout.createSequentialGroup()
                .addComponent(Return2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(dispRoomName2))
        );

        receiveRoom1.setText("[ENTER APPLIANCE NAME]");
        receiveRoom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveRoom1ActionPerformed(evt);
            }
        });

        confirmAdd1.setText("confirm");

        cancelAdd1.setText("cancel");

        javax.swing.GroupLayout applianceRegLayout = new javax.swing.GroupLayout(applianceReg);
        applianceReg.setLayout(applianceRegLayout);
        applianceRegLayout.setHorizontalGroup(
            applianceRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applianceRegLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(applianceRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receiveRoom1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(applianceRegLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(cancelAdd1)
                        .addGap(47, 47, 47)
                        .addComponent(confirmAdd1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(applianceTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        applianceRegLayout.setVerticalGroup(
            applianceRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applianceRegLayout.createSequentialGroup()
                .addComponent(applianceTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(receiveRoom1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addGroup(applianceRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelAdd1)
                    .addComponent(confirmAdd1))
                .addGap(253, 253, 253))
        );

        mainPanel.add(applianceReg, "applianceReg");
        applianceReg.getAccessibleContext().setAccessibleName("applianceReg");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomActionPerformed
        cardLayout.show(mainPanel,"roomReg");
    }//GEN-LAST:event_addRoomActionPerformed

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        cardLayout.show(mainPanel,"homescreen");
    }//GEN-LAST:event_ReturnActionPerformed

    private void appliance1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appliance1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appliance1ActionPerformed

    private void addRoom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoom1ActionPerformed
        cardLayout.show(mainPanel,"applianceReg");
    }//GEN-LAST:event_addRoom1ActionPerformed

    private void appliance3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appliance3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appliance3ActionPerformed

    private void appliance5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appliance5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appliance5ActionPerformed

    private void appliance8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appliance8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appliance8ActionPerformed

    private void appliance9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appliance9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appliance9ActionPerformed

    private void Return1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return1ActionPerformed
        cardLayout.show(mainPanel,"homescreen");
    }//GEN-LAST:event_Return1ActionPerformed

    private void room9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_room9ActionPerformed

    private void room7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_room7ActionPerformed

    private void room5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_room5ActionPerformed

    private void room4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_room4ActionPerformed

    private void room1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room1ActionPerformed
        cardLayout.show(mainPanel,"room");
    }//GEN-LAST:event_room1ActionPerformed

    private void receiveRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiveRoomActionPerformed

    private void Return2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return2ActionPerformed
        cardLayout.show(mainPanel,"room");
    }//GEN-LAST:event_Return2ActionPerformed

    private void receiveRoom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveRoom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiveRoom1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    private final CardLayout cardLayout;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomeScreen;
    private javax.swing.JButton Return;
    private javax.swing.JButton Return1;
    private javax.swing.JButton Return2;
    private javax.swing.JPanel Room;
    private javax.swing.JButton addRoom;
    private javax.swing.JButton addRoom1;
    private javax.swing.JButton appliance1;
    private javax.swing.JButton appliance10;
    private javax.swing.JButton appliance2;
    private javax.swing.JButton appliance3;
    private javax.swing.JButton appliance4;
    private javax.swing.JButton appliance5;
    private javax.swing.JButton appliance6;
    private javax.swing.JButton appliance7;
    private javax.swing.JButton appliance8;
    private javax.swing.JButton appliance9;
    private javax.swing.JPanel applianceReg;
    private javax.swing.JPanel applianceTop;
    private javax.swing.JButton cancelAdd;
    private javax.swing.JButton cancelAdd1;
    private javax.swing.JButton confirmAdd;
    private javax.swing.JButton confirmAdd1;
    private javax.swing.JLabel dispRoomName;
    private javax.swing.JLabel dispRoomName1;
    private javax.swing.JLabel dispRoomName2;
    private javax.swing.JLabel hiUser;
    private javax.swing.JPanel homeTop;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField receiveRoom;
    private javax.swing.JTextField receiveRoom1;
    private javax.swing.JButton room1;
    private javax.swing.JButton room10;
    private javax.swing.JButton room2;
    private javax.swing.JButton room3;
    private javax.swing.JButton room4;
    private javax.swing.JButton room5;
    private javax.swing.JButton room6;
    private javax.swing.JButton room7;
    private javax.swing.JButton room8;
    private javax.swing.JButton room9;
    private javax.swing.JPanel roomList;
    private javax.swing.JPanel roomList2;
    private javax.swing.JPanel roomReg;
    private javax.swing.JPanel roomRegTop;
    private javax.swing.JPanel roomTop;
    private javax.swing.JScrollPane scrollRoom;
    private javax.swing.JScrollPane scrollRoom1;
    // End of variables declaration//GEN-END:variables

}
